<?php

$service = new PHPSupabase\Service(
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrc3VwaWlpbGx1aHlwcnV1dGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE2Mjg2MTUsImV4cCI6MjAyNzIwNDYxNX0.dN8MDnQQKytz3ZIf3jnzq4AbOTqNBEpgeuGywKtd7uQ",
  "https://pksupiiilluhypruutka.supabase.co" 
);

if(isset($_SESSION['usuario'])){

  header("Location:index.php");
  exit;

}

$auth = $service->createAuth();

if ($_SERVER["REQUEST_METHOD"] === "POST") {

  $email = (isset($_POST["email"]) ? $_POST["email"] : null);
  $password = (isset($_POST["password"]) ? $_POST["password"] : null);

  try {
    $auth->signInWithEmailAndPassword($email, $password);
    $data = $auth->data(); // get the returned data generated by request
    if (isset($_SESSION['usuario'])){
        echo $data->access_token;
      }else{
        $_SESSION['usuario'] = $data->access_token;
        header("Location:index.php");
        exit;
      }
  } catch (Exception $e) {
    echo $auth->getError();
  }

}
?>
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="generator" content="">
  <title>Sign In</title>
  <link href="<?php echo $ruta?>/assets/css/globalstyles.css" rel="stylesheet">
  <link href="<?php echo $ruta?>/assets/css/signin.css" rel="stylesheet">
</head>

</body>
<main class="form">
  <div class="form__container">
    <a href="<?php echo $ruta?>index.php"><img src="./assets/img/fywiseaiwhitecolor.svg" width="260px" height="53px" alt=""></a>
    <form id="formularioInicioSesion" method="post">
      <h1 class="">Log In</h1>

      <div class="form__floating">
      <label for="floatingInput">Email</label>
      <input type="email" name="email" placeholder="name@host.com">
      </div>
      <div class="form__floating">
      <label for="floatingPassword">Password</label>
      <input type="password" name="password" placeholder="Password">
      <a href="<?php echo $ruta?>index.php?controlador=forgotpassword">Forgot your password?</a>
      </div>
      <button class="" type="submit">Log In</button>
      <div class="form__signup">
        <p class="">Need an account?</p>
        <a href="<?php echo $ruta?>index.php?controlador=signup">Sign up</a>
      </div>
    </form>
  </div>
</main>
</body>

</html>
